---
title: "Using LAGOSNEgis"
author: "Joseph Stachelek"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Using LAGOSNEgis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r message=FALSE, warning=FALSE, eval=FALSE}
library(LAGOSNEgis)
library(sf)
library(ggplot2)

res_iws  <- query_gis("IWS", "lagoslakeid", c(34352))
res_lake <- query_gis("LAGOS_NE_All_Lakes_4ha", "lagoslakeid", 34352)
res_pnt  <- query_gis("LAGOS_NE_All_Lakes_4ha_POINTS", "lagoslakeid", 34352)

ggplot() + 
  geom_sf(data = res_iws, color = "darkgreen") + 
  geom_sf(data = res_lake, color = "yellow") + 
  geom_sf(data = res_pnt, color = "blue")
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(LAGOSNEgis)
library(sf)
library(ggplot2)

ggplot() + 
  geom_sf(data = gis_34352$res_iws, color = "darkgreen") + 
  geom_sf(data = gis_34352$res_lake, color = "yellow") + 
  geom_sf(data = gis_34352$res_pnt, color = "blue")
```
